name: JMeter Plugin
description: Execute a JMeter script. It will run a JMeter script you specify and return the results CSV as well as a link to the HTML report generated.
version: 1.0
icon: https://cdn.rawgit.com/clarive/cla-jmeter-plugin/master/public/icon/logo-jmeter.svg?sanitize=true
url: https://github.com/clarive/cla-jmeter-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-jmeter-plugin
